
import { 
    default as makeWASocket, 
    useMultiFileAuthState, 
    DisconnectReason, 
    fetchLatestBaileysVersion, 
    delay,
    makeInMemoryStore
} from '@whiskeysockets/baileys';
import { Boom } from '@hapi/boom';
import express from 'express';
import QRCode from 'qrcode';
import fs from 'fs-extra';
import pino from 'pino';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 8080; 
const SESSION_DIR = './sessions';

app.use(express.json());
const logger = pino({ level: 'silent' });
const store = makeInMemoryStore({ logger });

let db = {
    stats: { sent: 0, received: 0, hits: 0 },
    settings: { ai_mode: true, auto_read: true, typing: true, anti_ban: true },
    inbox: [],
    logs: [],
    chartData: []
};

// Generate chart data dummy
const updateChartData = () => {
    const time = new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });
    db.chartData.push({ name: time, val: Math.floor(Math.random() * 100) });
    if (db.chartData.length > 20) db.chartData.shift();
};
setInterval(updateChartData, 60000);

let pendingNotifications = new Map();
let qrCodeData = null;
let isConnected = false;
let sock;

if (!fs.existsSync(SESSION_DIR)) {
    fs.mkdirSync(SESSION_DIR);
}

const buildPath = path.join(__dirname, 'dist');
app.use(express.static(buildPath));

async function startTitan() {
    const { state, saveCreds } = await useMultiFileAuthState(SESSION_DIR);
    const { version } = await fetchLatestBaileysVersion();
    
    sock = makeWASocket({ 
        version, 
        auth: state, 
        logger,
        browser: ["Andri Logistik Ultra", "Chrome", "15.0"],
        markOnlineOnConnect: true,
        printQRInTerminal: true
    });

    if (store) store.bind(sock.ev);

    sock.ev.on('connection.update', async (u) => {
        const { connection, lastDisconnect, qr } = u;
        if (qr) qrCodeData = await QRCode.toDataURL(qr);
        
        if (connection === 'open') { 
            isConnected = true; 
            qrCodeData = null; 
            console.log("✅ ANDRI LOGISTIK ENGINE v15.0 ACTIVE"); 
        }
        
        if (connection === 'close') { 
            isConnected = false; 
            const reason = new Boom(lastDisconnect?.error)?.output?.statusCode;
            if (reason !== DisconnectReason.loggedOut) startTitan(); 
        }
    });

    sock.ev.on('creds.update', saveCreds);

    sock.ev.on('messages.upsert', async ({ messages }) => {
        const m = messages[0];
        if (!m.message || m.key.fromMe) return;
        
        db.stats.received++;
        db.inbox.unshift({ 
            id: Date.now(),
            time: new Date().toLocaleTimeString(), 
            name: m.pushName || "Customer", 
            phone: m.key.remoteJid.split('@')[0], 
            msg: m.message.conversation || m.message.extendedTextMessage?.text || "Pesan Media"
        });
        if (db.inbox.length > 50) db.inbox.pop();
    });
}

// API KIRIM MASSAL DENGAN ANTI-BAN
app.post('/api/send-mass', async (req, res) => {
    const { messages } = req.body;
    if (!isConnected) return res.status(500).json({ error: "WA Disconnected" });
    
    res.json({ status: "processing", total: messages.length });

    for (const item of messages) {
        try {
            const phone = item.phone.replace(/[^0-9]/g, "");
            const jid = (phone.startsWith('0') ? '62' + phone.slice(1) : phone) + "@s.whatsapp.net";
            
            const variants = [
                `📦 *UPDATE ANDRI LOGISTIK*`,
                `📦 *INFO PAKET ANDRI LOGISTIK*`,
                `📦 *NOTIFIKASI PENGIRIMAN*`
            ];
            const header = variants[Math.floor(Math.random() * variants.length)];

            const text = `${header}\n\nHalo *${item.name}*,\n\nPaket Anda dengan resi *${item.resi}* saat ini berstatus: _${item.status}_\n\n━━━━━━━━━━━━━━━\n⚠️ *PENTING*:\n- *Mohon siapkan uang pas*\n- *Batas ambil maks 3 hari*\n━━━━━━━━━━━━━━━\n_Generated by Andri Engine v15.0_`;
            
            await sock.sendMessage(jid, { text });
            db.stats.sent++;
            
            // Jeda acak manusiawi
            await delay(5000 + Math.random() * 10000);
        } catch (e) {
            console.error("Batch send error:", e);
        }
    }
});

app.get('/api/status', (req, res) => {
    res.json({ 
        isConnected, 
        stats: db.stats, 
        inbox: db.inbox, 
        logs: db.logs, 
        qr: qrCodeData,
        chartData: db.chartData,
        system: { 
            ram: ((os.totalmem() - os.freemem())/1024/1024/1024).toFixed(2) + " GB", 
            cpu: (os.loadavg()[0]*10).toFixed(1) + "%" 
        }
    });
});

app.get('*', (req, res) => {
    const indexPath = path.join(buildPath, 'index.html');
    if (fs.existsSync(indexPath)) res.sendFile(indexPath);
    else res.status(404).send("Frontend build not found.");
});

app.listen(PORT, '0.0.0.0', () => {
    console.log(`🚀 Andri Logistik Engine running on port ${PORT}`);
    startTitan();
});
